language: cpp
install:
    - sudo apt-get update
    - sudo apt-get install libqt5network5 libqt5gui5 libqt5core5 libqt5multimedia5 qtmultimedia5-dev gstreamer0.10-fluendo-mp3 libpulse0 libpulse-dev libqt5dbus5
    - sudo apt-get install qt5-base qt5-qmake

script:
    - qmake -project
    - qmake doubanfm-qt.pro
    - make
