language: cpp
env:
    - QT_SELECT=qt5
before_install:
    - echo | sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update

install:
    - sudo apt-get install ubuntu-sdk

script:
    - qmake -project
    - qmake doubanfm-qt.pro
    - make
